
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: gcppubsub-source-sample
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: aex-messaging-vertx
